package com.onboardguard.shared.common.enums;

public enum ActionType {
    WATCHLIST_ENTRY_CREATE,
    WATCHLIST_ENTRY_UPDATE,
    WATCHLIST_ENTRY_ACTIVATE,
    WATCHLIST_ENTRY_DEACTIVATE,
    SCREENING_STRATEGY_SWITCH,
    RISK_THRESHOLD_UPDATE,
    FUZZY_MATCH_THRESHOLD_UPDATE,
    SLA_CONFIG_UPDATE,
    USER_CREATE,
    USER_ACTIVATE,
    USER_DEACTIVATE,
    USER_ROLE_UPDATE,
    UPDATE,
}
