package com.onboardguard.candidate.enums;

public enum OnboardingStatus {
    REGISTERED,
    PERSONAL_SAVED,
    PROFESSIONAL_SAVED,
    DOCUMENTS_UPLOADED,
    FORM_SUBMITTED,
    SCREENING_IN_PROGRESS,
    DOCUMENTS_UNDER_REVIEW,
    CASE_IN_REVIEW,
    SCREENING_CLEARED,
    FLAGGED,
    APPROVED,
    SCREENING_PENDING, DOCUMENTS_REJECTED, REJECTED
}